spring:
  profiles:
    active: RibbonClient8602
  application:
    name: RibbonClient

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8887/eureka/,http://peer2:8888/eureka/,http://peer3:8889/eureka/
server:
  port: 8601
spring:
  profiles: RibbonClient8601
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8887/eureka/,http://peer2:8888/eureka/,http://peer3:8889/eureka/
server:
  port: 8602
spring:
  profiles: RibbonClient8602




