spring:
  application:
    name: RibbonConsumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8887/eureka/,http://peer2:8888/eureka/,http://peer3:8889/eureka/
server:
  port: 8001







