spring:
  profiles:
    active: EurekaClient8601

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8887/eureka/,http://peer2:8888/eureka/,http://peer3:8889/eureka/
server:
  port: 8601
spring:
  application:
    name: EurekaClient8601
  profiles: EurekaClient8601
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8887/eureka/,http://peer2:8888/eureka/,http://peer3:8889/eureka/
server:
  port: 8602
spring:
  application:
    name: EurekaClient8602
  profiles: EurekaClient8602



