server:
  port: 8202
spring:
  application:
    name: ConfigServer
  profiles:
    active: configServer
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpanishSoap/spring-cloud-example.git
          search-paths: config
  profiles: configServer
---
#配置子目录存储
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpanishSoap/spring-cloud-example.git
          search-paths:  config/SubDirectoryConfigClient/,config/SubDirectoryConfigCommon/
  profiles: subdirectory
---
#高可用
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpanishSoap/spring-cloud-example.git
          search-paths:  config/SubDirectoryConfigClient/,config/SubDirectoryConfigCommon/
  profiles: haConfigServer
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8887/eureka/,http://peer2:8888/eureka/,http://peer3:8889/eureka/
