server:
  port: 8201
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpanishSoap/spring-cloud-example.git
          search-paths: config
