spring:
  application:
    name: hystrixConsumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    metadata-map:
#      cluster: consumer
server:
  port: 8105
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  hystrix:
    enabled: true
